theme: jekyll-theme-midnight
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>Mataji Kripa Pg</title>
  </head>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-info">
        <a class="navbar-brand" href="#">Mataji Kripa Pg</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">About Us</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
               Sharing
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="#">Double Seater</a>
                <a class="dropdown-item" href="#">Triple Seater</a>
            
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#" tabindex="-1" aria-disabled="true">Contact us</a>
            </li>
          </ul>
          <!-- <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form> -->
        </div>
      </nav>
      <!--Slider Section-->
      <div class="bd-example" >
        <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
          <ol class="carousel-indicators">
            <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
            <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
          </ol>
          <div class="carousel-inner" >
            <div class="carousel-item active">
              <img src="https://i.pinimg.com/736x/e3/19/63/e31963fb547f1e8511067e67bdddb329.jpg" class="d-block w-100"  height="400px" alt="...">
              <div class="carousel-caption d-none d-md-block">
               
              </div>
            </div>
            <div class="carousel-item">
              <img src="https://i0.wp.com/www.ariyonainterior.com/wp-content/uploads/2018/02/One-Room-Living-How-To-Organise-Your-Hostel-Room-19.jpg?resize=750%2C902&ssl=1" class="d-block w-100"  height="400px" alt="...">
              <div class="carousel-caption d-none d-md-block">
                
              </div>
            </div>
            <div class="carousel-item">
              <img src="https://www.westend61.de/images/0000882847pw/serious-teenage-girl-doing-homework-using-laptop-computer-at-home-CAVF25382.jpg" class="d-block w-100" height="400px"  alt="...">


              <div class="carousel-caption d-none d-md-block">
                
              </div>
            </div>
          </div>
          <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
      </div>
      <!--Facilities section-->
      <div class="row my-4">
        <div class="col-lg-4">
          <img src="https://cpimg.tistatic.com/06397820/b/4/Veg-Thali-Food-Delivery-Services-w300.jpg"  width="300" height="150">
          <!--svg class="bd-placeholder-img rounded-circle" width="140" height="140" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: 140x140"><title>Placeholder</title><rect width="100%" height="100%" fill="#777"></rect><text x="50%" y="50%" fill="#777" dy=".3em">140x140</text></svg-->
          <h2>Meal (Only Veg)</h2>
          <p>
          <ul>
            <li>Breakfast</li>
            <li>Lunch</li>
            <li>Dinner</li>
            <li>2 Time Tea</li>
          </ul>
        </p>
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
          <img src="https://www.deccanherald.com/sites/dh/files/styles/article_detail/public/articleimages/2022/02/04/paytm-reuters-1070137-1641894520-1077924-1643942971.jpg?itok=BF0sDk-E" width="300" height="150">
          <!--svg class="bd-placeholder-img rounded-circle" width="140" height="140" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: 140x140"><title>Placeholder</title><rect width="100%" height="100%" fill="#777"></rect><text x="50%" y="50%" fill="#777" dy=".3em">140x140</text></svg-->
          <h2>Mode of Payment</h2>
          <p>
            <ul>
              <li>Cash</li>
              <li>Google Pay</li>
              <li>Phone Pay</li>
              <li>Paytm</li>
              <li>Net Banking</li>
              
            </ul>
          </p>
          
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
          <img src= "https://www.thestatesman.com/wp-content/uploads/2017/10/drawing-room.jpg"width="300" height="150">
          
          <h2>Amenities</h2>
          <p>
            <ul>
              <li>Housekeeping</li>
              <li>Bedding</li>
              <li>Table & Chair</li>
              <li>Cupboard</li>
              <li>Geyser</li>
              <li>Fridge</li>
              <li>Water Purifier</li>
              <li>WiFi</li>
            </ul>
          </p>
          
        </div><!-- /.col-lg-4 -->
      </div>
       <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>
